import{a as S,S as B,i as a}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const q="https://pixabay.com/api/",E="51522694-741a1cf8502b1e4019d28362b";async function m(o,r){return(await S.get(q,{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const f=document.querySelector(".gallery"),g=document.querySelector(".load-more"),p=document.getElementById("loader"),$=new B(".gallery a");function h(o){const r=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:t,views:i,comments:w,downloads:v})=>`
    <li class="gallery-item">
      <a href="${s}">
        <img src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${t}</p>
        <p><b>Views</b> ${i}</p>
        <p><b>Comments</b> ${w}</p>
        <p><b>Downloads</b> ${v}</p>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",r),$.refresh()}function M(){f.innerHTML=""}function y(){p.classList.remove("hidden")}function b(){p.classList.add("hidden")}function H(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}let l="",c=1,d=0;const u=document.querySelector(".form"),I=document.querySelector(".load-more");u.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(r){l=r,c=1,M(),L(),y();try{const n=await m(l,c);if(d=n.totalHits,n.hits.length===0){a.info({message:"No images found. Try again.",position:"topRight"});return}h(n.hits),d>15&&H(),u.reset()}catch{a.error({message:"Something went wrong.",position:"topRight"})}finally{b()}}});I.addEventListener("click",async()=>{c+=1,y();try{const o=await m(l,c);h(o.hits),O(),document.querySelectorAll(".gallery-item").length>=d&&(L(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({message:"Error loading more images.",position:"topRight"})}finally{b()}});function O(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
