import{a as v,S,i as a}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const B="https://pixabay.com/api/",q="51522694-741a1cf8502b1e4019d28362b";async function u(o,r){return(await v.get(B,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".load-more"),g=document.getElementById("loader"),E=new S(".gallery a");function p(o){const r=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:t,views:i,comments:L,downloads:w})=>`
    <li class="gallery-item">
      <a href="${s}">
        <img src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${t}</p>
        <p><b>Views</b> ${i}</p>
        <p><b>Comments</b> ${L}</p>
        <p><b>Downloads</b> ${w}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",r),E.refresh()}function $(){m.innerHTML=""}function h(){g.classList.remove("hidden")}function y(){g.classList.add("hidden")}function M(){f.classList.remove("hidden")}function b(){f.classList.add("hidden")}let l="",c=1,d=0;const H=document.querySelector(".form"),I=document.querySelector(".load-more");H.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(r){l=r,c=1,$(),b(),h();try{const n=await u(l,c);if(d=n.totalHits,n.hits.length===0){a.info({message:"No images found. Try again.",position:"topRight"});return}p(n.hits),d>15&&M()}catch{a.error({message:"Something went wrong.",position:"topRight"})}finally{y()}}});I.addEventListener("click",async()=>{c+=1,h();try{const o=await u(l,c);p(o.hits),O(),document.querySelectorAll(".gallery-item").length>=d&&(b(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({message:"Error loading more images.",position:"topRight"})}finally{y()}});function O(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
